# version: '3.7'

# services: 
#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     image: myapp-server
#     container_name: myapp-node-server
#     volumes: 
#       - ./server/:/usr/src/app
#       - /usr/src/app/node_modules
#       - ./server/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
#     ports:
#       - "8080:8080"
#     depends_on:
#       - mysql
#     env_file: ./server/.env
#     environment:
#       - NODE_ENV=development
#     networks:
#       - app-network
#     command: ["./wait-for-it.sh", "-t", "60", "mysql:3306", "--", "npm", "start"]
#   mysql: 
#     image: mysql
#     volumes: 
#       - ./server/src/create_database.sql:/docker-entrypoint-initdb.d/0_init.sql
#     ports:
#       - "3306:3306"
#     networks:
#       - app-network
#     container_name: aucc-db
#     restart: always
#     environment:
#     - MYSQL_ROOT_PASSWORD=aucc
#     expose:
#       - "3306"
#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     image: myapp-client
#     container_name: myapp-react-client
#     command: yarn start
#     volumes: 
#       - ./client/:/usr/app
#       - /usr/app/node_modules
      
#     depends_on:
#       - mysql
#       - server
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network
#     tty: true

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   data-volume:
#   node_modules:
#   web-root:
#     driver: local


##PROD yml FOLLOWS
version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
    volumes: 
      - ./server/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - mysql
    networks:
      - app-network
    command: ["./wait-for-it.sh", "-t", "60", "mysql:3306", "--", "npm", "start"]
  mysql:
    image: mysql
    volumes: 
      - ./server/src/create_database.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    container_name: aucc-db
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=aucc
    expose:
      - "3306"

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local