const CLIENT_BUILD_PATH = path.join(__dirname, "../client/build");

// Static Files
app.use(express.static(CLIENT_BUILD_PATH));

// Server React Client
app.get("/", function(req, res) {
    res.sendFile(path.join(CLIENT_BUILD_PATH, "index.html"));
});